# 存放各种路由规则

spring:
  cloud:
    gateway:
      # 全局跨域
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-headers: '*'
            allowed-methods: '*'
      routes:
        - id: bing-route
          uri: https://cn.bing.com
          # 断言的短写法
#          predicates:
#            - Path=/**
          # 断言的长写法
          predicates:
            - name: Path
              args:
                patterns: /search
                matchTrailingSlash: true
            - name: Query
              # 必须带q参数且参数值是haha
              args:
                param: q
                regexp: haha
            # 自定义断言工厂短写法
#            - Vip=user,yiwenli
            # 自定义断言工厂长写法
            - name: Vip
              args:
                param: user
                value: yiwenli
          order: 99
        - id: order-route
          # 目的地
          uri: lb://service-order
          # 断言
          predicates:
            - Path=/api/order/**
          # 过滤器，只对当前规则生效
          filters:
            # 路径重写
            - RewritePath=/api/order/?(?<segment>.*), /$\{segment}
            # 自定义过滤器工厂
            - OnceToken=X-Response-Token, uuid
          order: 1
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          order: 2
      # 过滤器，对所有规则生效
      default-filters:
        - AddResponseHeader=X-Response-Abc, 123
